apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: custom-app
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest  # Use the desired MySQL image
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: welcome
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
