apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: custom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: linuxautobot/node-docker-app:7.0 
          ports:
            - containerPort: 9000

