apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: custom-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
  type: ClusterIP

